use std::collections::BTreeMap;

use chrono::NaiveDate;
use rust_decimal::Decimal;

use hledger_parser::ast::{
    AccountName, Cost, Journal, JournalItem, Posting, Status, Transaction,
};

use crate::account::AccountTree;
use crate::amount::MixedAmount;
use crate::error::LedgerError;

/// A resolved posting with computed amount.
#[derive(Debug, Clone)]
pub struct ResolvedPosting {
    pub account: AccountName,
    pub amount: MixedAmount,
    pub status: Status,
    /// Posting date: the `date:` tag override if present, else the txn date.
    pub date: NaiveDate,
    pub description: String,
    pub transaction_index: usize,
    pub comment: Option<String>,
    /// Unbalanced-virtual `(account)` posting: excluded from balancing and,
    /// like hledger's default reports, still included in balances.
    pub is_virtual: bool,
    /// Balanced-virtual `[account]` posting.
    pub virtual_balanced: bool,
    /// True for postings generated by an auto posting rule (`= query`).
    pub generated: bool,
    /// What this posting cost, when written with `@` or `@@`. Kept after
    /// resolution because cost basis and unrealised gain need it — the
    /// resolved `amount` alone only says how many units are held.
    pub cost: Option<MixedAmount>,
}

/// A resolved transaction with all amounts computed.
#[derive(Debug, Clone)]
pub struct ResolvedTransaction {
    pub date: NaiveDate,
    pub secondary_date: Option<NaiveDate>,
    pub status: Status,
    pub code: Option<String>,
    pub description: String,
    pub comment: Option<String>,
    pub postings: Vec<ResolvedPosting>,
    /// True when the transaction could not be balanced and was kept as
    /// written (lenient mode). Its amounts are what the file says; postings
    /// with no amount are zero. A warning carries the detail.
    pub unbalanced: bool,
}

/// A non-fatal problem discovered while resolving: shown to the user, never
/// hidden on stderr. Balance-assertion failures land here (hledger hard-errors;
/// an editor app must still open the file so the user can fix it — but the
/// failure must be loud).
#[derive(Debug, Clone, serde::Serialize)]
pub struct ResolveWarning {
    pub line: usize,
    pub message: String,
}

pub struct ResolveResult {
    pub transactions: Vec<ResolvedTransaction>,
    pub warnings: Vec<ResolveWarning>,
}

/// How to treat a transaction that cannot be balanced.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResolveOptions {
    /// `true`: an unbalanced transaction (or one with two elided amounts) is
    /// a hard error, like hledger — right for validating an edit before it
    /// is written. `false`: it becomes a warning and the transaction is kept
    /// as written and marked [`ResolvedTransaction::unbalanced`], so a
    /// journal with one bad entry still opens in the editor.
    pub strict: bool,
}

impl Default for ResolveOptions {
    fn default() -> Self {
        Self { strict: true }
    }
}

impl ResolveOptions {
    pub const STRICT: ResolveOptions = ResolveOptions { strict: true };
    pub const LENIENT: ResolveOptions = ResolveOptions { strict: false };
}

/// Process a journal's transactions: apply auto posting rules, infer missing
/// amounts (including balance assignments), validate balancing per hledger's
/// rules, and check balance assertions in date order. Strict: an unbalanced
/// transaction is an error.
pub fn resolve_transactions(journal: &Journal) -> Result<Vec<ResolvedTransaction>, LedgerError> {
    resolve_journal(journal).map(|r| r.transactions)
}

/// Strict resolution (see [`ResolveOptions`]).
pub fn resolve_journal(journal: &Journal) -> Result<ResolveResult, LedgerError> {
    resolve_journal_with(journal, ResolveOptions::STRICT)
}

/// Lenient resolution: never fails on the journal's content. Unbalanced
/// transactions are kept as written, marked, and reported as warnings.
pub fn resolve_journal_lenient(journal: &Journal) -> ResolveResult {
    match resolve_journal_with(journal, ResolveOptions::LENIENT) {
        Ok(result) => result,
        // Lenient mode converts every content problem to a warning; this
        // arm is unreachable but keeps the signature honest.
        Err(e) => ResolveResult {
            transactions: Vec::new(),
            warnings: vec![ResolveWarning {
                line: 0,
                message: e.to_string(),
            }],
        },
    }
}

pub fn resolve_journal_with(
    journal: &Journal,
    opts: ResolveOptions,
) -> Result<ResolveResult, LedgerError> {
    let mut warnings: Vec<ResolveWarning> = Vec::new();

    let transactions: Vec<&Transaction> = journal
        .items
        .iter()
        .filter_map(|item| match item {
            JournalItem::Transaction(t) => Some(t),
            _ => None,
        })
        .collect();

    let auto_rules: Vec<&hledger_parser::ast::AutoPostingRule> = journal
        .items
        .iter()
        .filter_map(|item| match item {
            JournalItem::AutoPostingRule(r) => Some(r),
            _ => None,
        })
        .collect();

    // Sort by date first (stable: parse order preserved within a date).
    let mut order: Vec<usize> = (0..transactions.len()).collect();
    order.sort_by_key(|&i| transactions[i].date);

    // Balance assignments and assertions see running balances in *posting*
    // date order, like hledger: a posting tagged `date:2024-01-20` inside a
    // 2024-01-10 transaction does not count towards an assertion dated
    // 2024-01-15. Every posting is streamed by (posting date, transaction
    // date order, posting order), and a transaction is resolved when its
    // first posting comes up.
    let mut stream: Vec<(NaiveDate, usize, usize)> = Vec::new();
    for (pos, &idx) in order.iter().enumerate() {
        let txn = transactions[idx];
        for (p_idx, posting) in txn.postings.iter().enumerate() {
            stream.push((posting.date.unwrap_or(txn.date), pos, p_idx));
        }
    }
    stream.sort();

    let mut resolved: Vec<Option<ResolvedTransaction>> = vec![None; order.len()];
    // Running balance per account (exclusive of subaccounts).
    let mut running: BTreeMap<String, MixedAmount> = BTreeMap::new();

    let resolve_at = |pos: usize,
                          running: &mut BTreeMap<String, MixedAmount>,
                          warnings: &mut Vec<ResolveWarning>|
     -> Result<ResolvedTransaction, LedgerError> {
        let idx = order[pos];
        let txn = transactions[idx];
        let mut resolved_txn = match resolve_transaction(txn, idx, running) {
            Ok(r) => r,
            Err(e) if !opts.strict => {
                warnings.push(ResolveWarning {
                    line: txn.span.line,
                    message: e.to_string(),
                });
                unbalanced_as_written(txn, idx)
            }
            Err(e) => return Err(e),
        };

        // Apply auto posting rules (after inference, like hledger --auto).
        for rule in &auto_rules {
            apply_auto_rule(rule, txn, &mut resolved_txn, warnings);
        }

        // Generated postings carry no assertions; they join the running
        // balances as soon as the transaction exists.
        for posting in resolved_txn.postings.iter().filter(|p| p.generated) {
            let balance = running
                .entry(posting.account.full.clone())
                .or_insert_with(MixedAmount::zero);
            if let Err(e) = balance.try_add_mixed(&posting.amount) {
                warnings.push(ResolveWarning {
                    line: txn.span.line,
                    message: format!("{} (running balance of {})", e, posting.account.full),
                });
            }
        }
        Ok(resolved_txn)
    };

    for &(_, pos, p_idx) in &stream {
        if resolved[pos].is_none() {
            resolved[pos] = Some(resolve_at(pos, &mut running, &mut warnings)?);
        }
        let txn = transactions[order[pos]];
        let resolved_txn = resolved[pos].as_ref().expect("resolved above");
        let Some(posting) = resolved_txn.postings.get(p_idx) else {
            continue;
        };
        let ast_posting = &txn.postings[p_idx];
        let line = ast_posting.span.line.max(txn.span.line);

        let balance = running
            .entry(posting.account.full.clone())
            .or_insert_with(MixedAmount::zero);
        if let Err(e) = balance.try_add_mixed(&posting.amount) {
            warnings.push(ResolveWarning {
                line,
                message: format!("{} (running balance of {})", e, posting.account.full),
            });
        }

        let Some(assertion) = &ast_posting.balance_assertion else {
            continue;
        };
        let actual = if assertion.inclusive {
            // Include subaccounts.
            let prefix = format!("{}:", posting.account.full);
            let mut total = running
                .get(&posting.account.full)
                .cloned()
                .unwrap_or_default();
            for (acct, amt) in running.iter() {
                if acct.starts_with(&prefix) {
                    total.add_mixed(amt);
                }
            }
            total
        } else {
            running
                .get(&posting.account.full)
                .cloned()
                .unwrap_or_default()
        };

        // hledger compares assertions exactly (1.50.3: `$100.404` against
        // `= $100.40` fails even with a two-decimal commodity directive),
        // not at the precision the assertion happens to be written in.
        let got = actual.get(&assertion.commodity);
        if got != assertion.quantity {
            warnings.push(ResolveWarning {
                line,
                message: format!(
                    "Balance assertion failed: {} expected {} {}, got {} {}",
                    posting.account.full,
                    assertion.quantity,
                    assertion.commodity,
                    got,
                    assertion.commodity,
                ),
            });
        } else if assertion.strong {
            // `==` also asserts no other commodities are present.
            for (commodity, qty) in &actual.amounts {
                if commodity != &assertion.commodity && !qty.is_zero() {
                    warnings.push(ResolveWarning {
                        line,
                        message: format!(
                            "Strong assertion failed: {} also holds {} {}",
                            posting.account.full, qty, commodity,
                        ),
                    });
                    break;
                }
            }
        }
    }

    // Transactions without postings never entered the stream.
    for pos in 0..order.len() {
        if resolved[pos].is_none() {
            resolved[pos] = Some(resolve_at(pos, &mut running, &mut warnings)?);
        }
    }

    Ok(ResolveResult {
        transactions: resolved.into_iter().map(|t| t.expect("all resolved")).collect(),
        warnings,
    })
}

/// Half of one unit at the given display precision: hledger considers a
/// transaction balanced when each commodity's sum is zero at display precision.
fn tolerance_for_precision(precision: u8) -> Decimal {
    let mut t = Decimal::new(5, 1); // 0.5
    for _ in 0..precision {
        t = t / Decimal::TEN;
    }
    t
}

fn overflow(what: impl std::fmt::Display) -> LedgerError {
    LedgerError::Overflow {
        message: what.to_string(),
    }
}

/// Balancing contribution of a posting: the cost side when a cost is present.
fn balancing_amount(posting: &Posting) -> Result<Option<MixedAmount>, LedgerError> {
    let Some(amt) = posting.amount.as_ref() else {
        return Ok(None);
    };
    let quantity = amt.quantity;
    Ok(Some(match &amt.cost {
        Some(Cost::UnitCost(c)) => {
            let total = quantity
                .checked_mul(c.quantity)
                .ok_or_else(|| overflow(format!("{} {} @ {} {}", quantity, amt.commodity, c.quantity, c.commodity)))?;
            MixedAmount::single(&c.commodity, total)
        }
        Some(Cost::TotalCost(c)) => {
            let cost_total = if quantity.is_sign_negative() {
                -c.quantity
            } else {
                c.quantity
            };
            MixedAmount::single(&c.commodity, cost_total)
        }
        None => MixedAmount::single(&amt.commodity, quantity),
    }))
}

/// A transaction kept exactly as written because it could not be balanced:
/// explicit amounts stand, elided ones are zero. Only reached in lenient
/// mode, after the problem has been reported.
fn unbalanced_as_written(txn: &Transaction, index: usize) -> ResolvedTransaction {
    let postings = txn
        .postings
        .iter()
        .map(|posting| {
            let amount = posting
                .amount
                .as_ref()
                .map(|a| MixedAmount::single(&a.commodity, a.quantity))
                .unwrap_or_default();
            ResolvedPosting {
                account: posting.account.clone(),
                amount,
                status: effective_status(txn.status, posting.status),
                date: posting.date.unwrap_or(txn.date),
                description: txn.description.clone(),
                transaction_index: index,
                comment: posting.comment.as_ref().map(|c| c.text.clone()),
                is_virtual: posting.is_virtual,
                virtual_balanced: posting.virtual_balanced,
                generated: false,
                cost: balancing_amount(posting).ok().flatten(),
            }
        })
        .collect();
    ResolvedTransaction {
        date: txn.date,
        secondary_date: txn.secondary_date,
        status: txn.status,
        code: txn.code.clone(),
        description: txn.description.clone(),
        comment: txn.comment.as_ref().map(|c| c.text.clone()),
        postings,
        unbalanced: true,
    }
}

/// Resolve a single transaction: compute balance assignments, infer missing
/// amounts, and validate balancing. Real postings and balanced-virtual
/// postings balance as independent groups; unbalanced-virtual postings are
/// excluded entirely (hledger semantics).
fn resolve_transaction(
    txn: &Transaction,
    index: usize,
    running: &BTreeMap<String, MixedAmount>,
) -> Result<ResolvedTransaction, LedgerError> {
    #[derive(PartialEq, Clone, Copy)]
    enum Group {
        Real,
        BalancedVirtual,
        UnbalancedVirtual,
    }

    let group_of = |p: &Posting| {
        if !p.is_virtual {
            Group::Real
        } else if p.virtual_balanced {
            Group::BalancedVirtual
        } else {
            Group::UnbalancedVirtual
        }
    };

    // First pass: compute each posting's amount, resolving balance assignments
    // from running balances.
    let mut amounts: Vec<Option<MixedAmount>> = Vec::with_capacity(txn.postings.len());
    for posting in &txn.postings {
        if let Some(amt) = &posting.amount {
            amounts.push(Some(MixedAmount::single(&amt.commodity, amt.quantity)));
        } else if let Some(assertion) = &posting.balance_assertion {
            // Balance assignment: amount = asserted balance - current balance.
            let current = running.get(&posting.account.full).cloned().unwrap_or_default();
            let delta = assertion
                .quantity
                .checked_sub(current.get(&assertion.commodity))
                .ok_or_else(|| overflow(format!("balance assignment on {}", posting.account.full)))?;
            let mut amount = MixedAmount::single(&assertion.commodity, delta);
            if assertion.strong {
                // `==` assignment: hledger sets the whole balance, so every
                // other commodity the account holds is zeroed here.
                for (commodity, qty) in &current.amounts {
                    if commodity != &assertion.commodity {
                        amount.try_add(commodity, -*qty)?;
                    }
                }
            }
            amounts.push(Some(amount));
        } else {
            amounts.push(None);
        }
    }

    // Balance each group independently.
    for group in [Group::Real, Group::BalancedVirtual] {
        let member_idxs: Vec<usize> = (0..txn.postings.len())
            .filter(|&i| group_of(&txn.postings[i]) == group)
            .collect();
        if member_idxs.is_empty() {
            continue;
        }

        let missing: Vec<usize> = member_idxs
            .iter()
            .copied()
            .filter(|&i| amounts[i].is_none())
            .collect();
        if missing.len() > 1 {
            return Err(LedgerError::MultipleInferredAmounts {
                line: txn.span.line,
            });
        }

        // Sum of explicit amounts, cost-converted where costs exist.
        let mut sum = MixedAmount::zero();
        let mut has_costs = false;
        let mut max_precision: BTreeMap<String, u8> = BTreeMap::new();
        for &i in &member_idxs {
            let posting = &txn.postings[i];
            if let Some(amt) = &posting.amount {
                // The tolerance commodity/precision follow the balancing side:
                // the cost commodity (at combined precision) when a cost exists.
                let this_prec = match &amt.cost {
                    Some(Cost::UnitCost(c)) => {
                        has_costs = true;
                        (amt.style.precision as u32 + c.style.precision as u32).min(10) as u8
                    }
                    Some(Cost::TotalCost(c)) => {
                        has_costs = true;
                        c.style.precision
                    }
                    None => amt.style.precision,
                };
                let prec = max_precision.entry(commodity_of_balance(posting)).or_insert(0);
                *prec = (*prec).max(this_prec);
                let contribution = balancing_amount(posting)?.expect("posting has an amount");
                sum.try_add_mixed(&contribution)
                    .map_err(|_| overflow(format!("line {}: the postings' sum", txn.span.line)))?;
            } else if let Some(m) = &amounts[i] {
                // Balance assignment resolved above.
                sum.try_add_mixed(m)
                    .map_err(|_| overflow(format!("line {}: the postings' sum", txn.span.line)))?;
            }
        }

        if let Some(&mi) = missing.first() {
            // Inferred amount is the negation of the group sum.
            amounts[mi] = Some(sum.negate());
            continue;
        }

        // All amounts explicit: every commodity must balance at display
        // precision — except the two-commodity, no-cost case, which hledger
        // reads as an implicit conversion.
        let nonzero: Vec<(&String, &Decimal)> = sum
            .amounts
            .iter()
            .filter(|(c, q)| {
                let tol = tolerance_for_precision(*max_precision.get(*c).unwrap_or(&2));
                q.abs() > tol
            })
            .collect();

        if nonzero.is_empty() {
            continue;
        }
        if !has_costs && nonzero.len() == 2 {
            // Implicit conversion between exactly two commodities.
            continue;
        }
        let detail = nonzero
            .iter()
            .map(|(c, q)| format!("{} {}", q, c))
            .collect::<Vec<_>>()
            .join(", ");
        return Err(LedgerError::UnbalancedTransaction {
            line: txn.span.line,
            message: format!(
                "the {} postings' sum should be 0 but is: {}",
                match group {
                    Group::Real => "real",
                    _ => "balanced virtual",
                },
                detail
            ),
        });
    }

    // Unbalanced-virtual postings must have explicit amounts.
    for (i, posting) in txn.postings.iter().enumerate() {
        if group_of(posting) == Group::UnbalancedVirtual && amounts[i].is_none() {
            return Err(LedgerError::Other(format!(
                "line {}: virtual posting ({}) needs an explicit amount",
                txn.span.line, posting.account.full
            )));
        }
    }

    let mut resolved_postings = Vec::with_capacity(txn.postings.len());
    for (posting, amount) in txn.postings.iter().zip(amounts.into_iter()) {
        resolved_postings.push(ResolvedPosting {
            account: posting.account.clone(),
            amount: amount.unwrap_or_default(),
            status: effective_status(txn.status, posting.status),
            date: posting.date.unwrap_or(txn.date),
            description: txn.description.clone(),
            transaction_index: index,
            comment: posting.comment.as_ref().map(|c| c.text.clone()),
            is_virtual: posting.is_virtual,
            virtual_balanced: posting.virtual_balanced,
            generated: false,
            cost: balancing_amount(posting)?,
        });
    }

    Ok(ResolvedTransaction {
        date: txn.date,
        secondary_date: txn.secondary_date,
        status: txn.status,
        code: txn.code.clone(),
        description: txn.description.clone(),
        comment: txn.comment.as_ref().map(|c| c.text.clone()),
        postings: resolved_postings,
        unbalanced: false,
    })
}

/// A posting's transaction-level status flows down to unmarked postings.
fn effective_status(txn_status: Status, posting_status: Status) -> Status {
    match posting_status {
        Status::Unmarked => txn_status,
        other => other,
    }
}

fn commodity_of_balance(posting: &Posting) -> String {
    match posting.amount.as_ref() {
        Some(amt) => match &amt.cost {
            Some(Cost::UnitCost(c)) | Some(Cost::TotalCost(c)) => c.commodity.clone(),
            None => amt.commodity.clone(),
        },
        None => String::new(),
    }
}

/// Apply one auto posting rule to a resolved transaction. The rule's query is
/// interpreted as hledger's default account-regex terms (space-separated
/// alternatives, optional `acct:` prefix). Unsupported query syntax disables
/// the rule with a warning rather than silently matching wrongly.
fn apply_auto_rule(
    rule: &hledger_parser::ast::AutoPostingRule,
    ast_txn: &Transaction,
    resolved: &mut ResolvedTransaction,
    warnings: &mut Vec<ResolveWarning>,
) {
    let mut patterns: Vec<regex::Regex> = Vec::new();
    for term in rule.query.split_whitespace() {
        let term = term.strip_prefix("acct:").unwrap_or(term);
        if term.contains(':') && !term.starts_with('^') {
            // Might be another query type (amt:, date:, tag: ...) we don't
            // support; account names contain ':' too, so only treat known
            // prefixes as unsupported.
            let known_unsupported = ["amt", "date", "desc", "tag", "status", "cur", "real", "not", "payee", "code", "note", "type", "depth"]
                .iter()
                .any(|p| term.starts_with(&format!("{}:", p)));
            if known_unsupported {
                warnings.push(ResolveWarning {
                    line: rule.span.line,
                    message: format!(
                        "auto posting rule query '{}' uses unsupported syntax; rule not applied",
                        rule.query
                    ),
                });
                return;
            }
        }
        match regex::Regex::new(&format!("(?i){}", term)) {
            Ok(re) => patterns.push(re),
            Err(_) => {
                warnings.push(ResolveWarning {
                    line: rule.span.line,
                    message: format!("invalid regex in auto posting rule: {}", term),
                });
                return;
            }
        }
    }
    if patterns.is_empty() {
        return;
    }

    let mut generated: Vec<ResolvedPosting> = Vec::new();
    for posting in &resolved.postings {
        // hledger matches virtual postings too (`= expenses:food` fires on
        // `(expenses:food) $7`); only postings a rule generated are skipped.
        if posting.generated {
            continue;
        }
        if !patterns.iter().any(|re| re.is_match(&posting.account.full)) {
            continue;
        }
        // Build this rule's postings for the matched posting. One of them may
        // omit its amount, which hledger infers so the generated set balances
        // — a rule like `expenses:carbon $5 / liabilities:offset` depends on
        // it. Dropping that posting, as this used to, left the books short.
        let mut batch: Vec<ResolvedPosting> = Vec::new();
        let mut elided: Option<usize> = None;
        for rule_posting in &rule.postings {
            let amount = match &rule_posting.amount {
                Some(rule_amt) if rule_amt.multiplier => {
                    // Scale the matched posting's amount(s).
                    match posting.amount.try_scale(rule_amt.quantity) {
                        Ok(m) => m,
                        Err(e) => {
                            warnings.push(ResolveWarning {
                                line: rule.span.line,
                                message: format!(
                                    "auto posting rule '{}' not applied to '{}': {}",
                                    rule.query, ast_txn.description, e
                                ),
                            });
                            return;
                        }
                    }
                }
                Some(rule_amt) => MixedAmount::single(&rule_amt.commodity, rule_amt.quantity),
                None => {
                    if elided.is_some() {
                        warnings.push(ResolveWarning {
                            line: rule.span.line,
                            message: format!(
                                "auto posting rule '{}' leaves more than one amount blank; only one can be inferred",
                                rule.query
                            ),
                        });
                        continue;
                    }
                    elided = Some(batch.len());
                    MixedAmount::zero()
                }
            };
            batch.push(ResolvedPosting {
                account: rule_posting.account.clone(),
                amount,
                status: resolved.status,
                date: resolved.date,
                description: resolved.description.clone(),
                transaction_index: resolved.postings.first().map(|p| p.transaction_index).unwrap_or(0),
                comment: None,
                is_virtual: rule_posting.is_virtual,
                virtual_balanced: rule_posting.virtual_balanced,
                generated: true,
                // Auto postings carry no cost of their own.
                cost: None,
            });
        }

        // Infer the blank one from the others in its balancing group; an
        // unbalanced-virtual posting balances against nothing.
        if let Some(idx) = elided {
            let target_virtual = batch[idx].is_virtual;
            let mut sum = MixedAmount::zero();
            for (i, p) in batch.iter().enumerate() {
                if i != idx && p.is_virtual == target_virtual {
                    sum.add_mixed(&p.amount);
                }
            }
            batch[idx].amount = sum.negate();
        }

        generated.extend(batch);
    }

    if generated.is_empty() {
        return;
    }

    // Sanity: generated REAL postings should balance; warn if they don't
    // (hledger --auto errors here; we keep the journal usable but loud).
    let mut real_sum = MixedAmount::zero();
    let mut has_real = false;
    for p in &generated {
        if !p.is_virtual {
            has_real = true;
            real_sum.add_mixed(&p.amount);
        }
    }
    if has_real && !real_sum.is_zero() {
        warnings.push(ResolveWarning {
            line: rule.span.line,
            message: format!(
                "auto posting rule '{}' generated unbalanced real postings ({}) for transaction '{}' on {}",
                rule.query, real_sum, ast_txn.description, ast_txn.date
            ),
        });
    }

    resolved.postings.extend(generated);
}

/// Build an account tree from resolved transactions.
pub fn build_account_tree(transactions: &[ResolvedTransaction]) -> AccountTree {
    let mut tree = AccountTree::new();

    for txn in transactions {
        for posting in &txn.postings {
            tree.add_to_account(&posting.account, &posting.amount);
        }
    }

    tree.compute_balances();
    tree
}

#[cfg(test)]
mod tests {
    use super::*;
    use hledger_parser::parse;
    use rust_decimal_macros::dec;

    fn parse_and_resolve(input: &str) -> Vec<ResolvedTransaction> {
        let journal = parse(input).unwrap();
        resolve_transactions(&journal).unwrap()
    }

    fn parse_full(input: &str) -> ResolveResult {
        let journal = parse(input).unwrap();
        resolve_journal(&journal).unwrap()
    }

    #[test]
    fn infer_missing_amount() {
        let txns = parse_and_resolve(
            "2024-01-15 Test\n    expenses:food  $50.00\n    assets:checking\n",
        );
        assert_eq!(txns.len(), 1);
        assert_eq!(txns[0].postings.len(), 2);
        assert_eq!(txns[0].postings[1].amount.get("$"), dec!(-50.00));
    }

    #[test]
    fn explicit_balanced_transaction() {
        let txns = parse_and_resolve(
            "2024-01-15 Test\n    expenses:food  $50.00\n    assets:checking  $-50.00\n",
        );
        assert_eq!(txns.len(), 1);
        assert_eq!(txns[0].postings[0].amount.get("$"), dec!(50.00));
        assert_eq!(txns[0].postings[1].amount.get("$"), dec!(-50.00));
    }

    #[test]
    fn unbalanced_transaction_errors() {
        let journal = parse(
            "2024-01-15 Test\n    expenses:food  $50.00\n    assets:checking  $-40.00\n",
        )
        .unwrap();
        assert!(resolve_transactions(&journal).is_err());
    }

    #[test]
    fn unbalanced_with_cost_errors() {
        // hledger: "This multi-commodity transaction is unbalanced."
        let journal = parse(
            "2024-01-15 Bad\n    assets:stock  1 AAPL @ 100 USD\n    assets:cash  -999 USD\n",
        )
        .unwrap();
        assert!(resolve_transactions(&journal).is_err());
    }

    #[test]
    fn balanced_with_cost_ok() {
        let txns = parse_and_resolve(
            "2024-01-15 Buy\n    assets:stock  1 AAPL @ 100 USD\n    assets:cash  -100 USD\n",
        );
        assert_eq!(txns.len(), 1);
    }

    #[test]
    fn three_commodity_no_cost_imbalance_errors() {
        // hledger errors on 3+ commodities without costs.
        let journal = parse(
            "2024-01-15 Bad\n    a  100 USD\n    b  -90 EUR\n    c  5 GBP\n",
        )
        .unwrap();
        assert!(resolve_transactions(&journal).is_err());
    }

    #[test]
    fn two_commodity_implicit_conversion_ok() {
        let txns = parse_and_resolve(
            "2024-01-15 FX\n    assets:eur  100 EUR\n    assets:usd  -110 USD\n",
        );
        assert_eq!(txns.len(), 1);
    }

    #[test]
    fn multiple_inferred_amounts_errors() {
        let journal =
            parse("2024-01-15 Test\n    expenses:food\n    assets:checking\n").unwrap();
        assert!(resolve_transactions(&journal).is_err());
    }

    #[test]
    fn multicurrency_with_cost_allowed() {
        let txns = parse_and_resolve(
            "2024-01-15 Exchange\n    assets:eur  100.00 EUR @ $1.10\n    assets:usd\n",
        );
        assert_eq!(txns.len(), 1);
        // Inferred posting balances the cost side.
        assert_eq!(txns[0].postings[1].amount.get("$"), dec!(-110.00));
    }

    #[test]
    fn virtual_posting_excluded_from_balancing() {
        // hledger: (budget:food) is unbalanced-virtual; assets:bank gets 1000.
        let txns = parse_and_resolve(
            "2024-01-15 Pay\n    (budget:food)  200 USD\n    income:job  -1000 USD\n    assets:bank\n",
        );
        assert_eq!(txns[0].postings[2].amount.get("USD"), dec!(1000));
    }

    #[test]
    fn virtual_posting_does_not_unbalance_explicit_txn() {
        let txns = parse_and_resolve(
            "2024-01-15 Pay\n    (budget:food)  200 USD\n    income:job  -1000 USD\n    assets:bank  1000 USD\n",
        );
        assert_eq!(txns.len(), 1);
    }

    #[test]
    fn balanced_virtual_group_checked_separately() {
        let txns = parse_and_resolve(
            "2024-01-15 T\n    [budget:food]  50 USD\n    [budget:available]  -50 USD\n    expenses:food  50 USD\n    assets:cash  -50 USD\n",
        );
        assert_eq!(txns.len(), 1);

        let journal = parse(
            "2024-01-15 T\n    [budget:food]  50 USD\n    [budget:available]  -40 USD\n    expenses:food  50 USD\n    assets:cash  -50 USD\n",
        )
        .unwrap();
        assert!(resolve_transactions(&journal).is_err());
    }

    #[test]
    fn balance_assignment_computes_amount() {
        let txns = parse_and_resolve(
            "2024-01-01 Opening\n    assets:bank  $100\n    equity:opening\n\n\
             2024-02-01 Set balance\n    assets:bank  = $500\n    equity:adjustment\n",
        );
        // Assignment: bank goes from 100 to 500, so the posting is +400.
        assert_eq!(txns[1].postings[0].amount.get("$"), dec!(400));
        assert_eq!(txns[1].postings[1].amount.get("$"), dec!(-400));
    }

    #[test]
    fn assertion_failure_is_warning_not_stderr() {
        let result = parse_full(
            "2024-01-01 A\n    assets:bank  $100\n    equity\n\n\
             2024-01-02 B\n    assets:bank  $50 = $999\n    equity\n",
        );
        assert_eq!(result.warnings.len(), 1);
        assert!(result.warnings[0].message.contains("assertion failed"));
    }

    #[test]
    fn assertion_success_no_warning() {
        let result = parse_full(
            "2024-01-01 A\n    assets:bank  $100 = $100\n    equity\n\n\
             2024-01-02 B\n    assets:bank  $50 = $150\n    equity\n",
        );
        assert!(result.warnings.is_empty(), "warnings: {:?}", result.warnings);
    }

    #[test]
    fn inclusive_assertion_includes_subaccounts() {
        let result = parse_full(
            "2024-01-01 A\n    assets:bank:a  $100\n    equity\n\n\
             2024-01-02 B\n    assets:bank:b  $50\n    equity\n\n\
             2024-01-03 C\n    assets:bank  $10 =* $160\n    equity\n",
        );
        assert!(result.warnings.is_empty(), "warnings: {:?}", result.warnings);
    }

    #[test]
    fn auto_posting_applied_with_multiplier() {
        let txns = parse_and_resolve(
            "= expenses:food\n    (budget:food)  *2\n\n\
             2024-01-15 Grocery\n    expenses:food  $10\n    assets:cash\n",
        );
        assert_eq!(txns[0].postings.len(), 3);
        let generated = &txns[0].postings[2];
        assert_eq!(generated.account.full, "budget:food");
        assert_eq!(generated.amount.get("$"), dec!(20));
        assert!(generated.generated);
    }

    #[test]
    fn auto_posting_fixed_amount_pair() {
        let txns = parse_and_resolve(
            "= expenses:food\n    assets:savings:tax  $5.00\n    assets:checking  $-5.00\n\n\
             2024-01-15 Grocery\n    expenses:food  $10\n    assets:cash\n",
        );
        assert_eq!(txns[0].postings.len(), 4);
    }

    #[test]
    fn posting_status_inherits_txn_status() {
        let txns = parse_and_resolve(
            "2024-01-15 * Cleared\n    expenses:food  $10\n    assets:cash\n",
        );
        assert_eq!(txns[0].postings[0].status, Status::Cleared);
    }

    #[test]
    fn posting_date_tag_overrides() {
        let txns = parse_and_resolve(
            "2024-01-15 T\n    expenses:food  $10 ; date:2024-01-20\n    assets:cash\n",
        );
        assert_eq!(
            txns[0].postings[0].date,
            NaiveDate::from_ymd_opt(2024, 1, 20).unwrap()
        );
        assert_eq!(
            txns[0].postings[1].date,
            NaiveDate::from_ymd_opt(2024, 1, 15).unwrap()
        );
    }

    #[test]
    fn transactions_sorted_by_date() {
        let txns = parse_and_resolve(
            "2024-01-20 Later\n    expenses:a  $10\n    assets:b\n\n\
             2024-01-10 Earlier\n    expenses:a  $20\n    assets:b\n",
        );
        assert_eq!(txns[0].description, "Earlier");
        assert_eq!(txns[1].description, "Later");
    }

    #[test]
    fn build_tree_from_transactions() {
        let txns = parse_and_resolve(
            "2024-01-15 Test\n    expenses:food  $50.00\n    assets:checking  $-50.00\n",
        );
        let tree = build_account_tree(&txns);

        assert_eq!(tree.accounts["expenses:food"].balance.get("$"), dec!(50.00));
        assert_eq!(tree.accounts["expenses"].balance.get("$"), dec!(50.00));
        assert_eq!(
            tree.accounts["assets:checking"].balance.get("$"),
            dec!(-50.00)
        );
        assert_eq!(tree.accounts["assets"].balance.get("$"), dec!(-50.00));
    }

    #[test]
    fn three_posting_transaction() {
        let txns = parse_and_resolve(
            "2024-01-15 Split\n    expenses:food  $30.00\n    expenses:drink  $20.00\n    assets:checking\n",
        );
        assert_eq!(txns[0].postings[2].amount.get("$"), dec!(-50.00));
    }

    #[test]
    fn rounding_tolerance_at_display_precision() {
        // Sums that differ only beyond display precision balance (hledger).
        let txns = parse_and_resolve(
            "2024-01-15 T\n    a  $33.33\n    b  $33.33\n    c  $33.34\n    d  $-100.00\n",
        );
        assert_eq!(txns.len(), 1);
    }

    #[test]
    fn assertions_follow_posting_dates() {
        // hledger 1.50.3: the $10 posting dated 01-20 is not in x's balance
        // when the 01-15 assertion is checked, so `= $5` holds and `= $15`
        // fails.
        let ok = parse_full(
            "2024-01-10 a\n    x  $10 ; date:2024-01-20\n    y\n\n\
             2024-01-15 b\n    x  $5 = $5\n    y\n",
        );
        assert!(ok.warnings.is_empty(), "warnings: {:?}", ok.warnings);
        let bad = parse_full(
            "2024-01-10 a\n    x  $10 ; date:2024-01-20\n    y\n\n\
             2024-01-15 b\n    x  $5 = $15\n    y\n",
        );
        assert_eq!(bad.warnings.len(), 1, "warnings: {:?}", bad.warnings);
        // Output order is still transaction date order.
        assert_eq!(bad.transactions[0].description, "a");
    }

    #[test]
    fn assertions_are_compared_exactly() {
        // hledger: `$0 = $100` against $100.40 fails, whatever the precision
        // the assertion is written in.
        let r = parse_full("2024-01-01 x\n    a  $100.40\n    b\n\n2024-01-02 y\n    a  $0 = $100\n    b\n");
        assert_eq!(r.warnings.len(), 1);
        let r = parse_full("2024-01-01 x\n    a  $100.404\n    b\n\n2024-01-02 y\n    a  $0 = $100.40\n    b\n");
        assert_eq!(r.warnings.len(), 1);
        let r = parse_full("2024-01-01 x\n    a  $100.404\n    b\n\n2024-01-02 y\n    a  $0 = $100.404\n    b\n");
        assert!(r.warnings.is_empty());
    }

    #[test]
    fn strong_assignment_zeroes_other_commodities() {
        // hledger: after `x  == $20`, x holds only $20 (bal x shows no EUR).
        let r = parse_full(
            "2024-01-01 a\n    x  $10\n    y\n\n\
             2024-01-02 b\n    x  5 EUR\n    y\n\n\
             2024-01-03 c\n    x  == $20\n    y\n",
        );
        assert!(r.warnings.is_empty(), "warnings: {:?}", r.warnings);
        let tree = build_account_tree(&r.transactions);
        assert_eq!(tree.accounts["x"].balance.get("$"), dec!(20));
        assert_eq!(tree.accounts["x"].balance.get("EUR"), dec!(0));
        // The assignment posting itself carried the +$10 and the -5 EUR.
        let p = &r.transactions[2].postings[0];
        assert_eq!(p.amount.get("$"), dec!(10));
        assert_eq!(p.amount.get("EUR"), dec!(-5));
    }

    #[test]
    fn auto_rules_match_virtual_postings() {
        // hledger print --auto: `= expenses:food` fires on `(expenses:food) $7`.
        let txns = parse_and_resolve(
            "= expenses:food\n    (budget:food)  *-1\n\n2024-01-01 x\n    (expenses:food)  $7\n",
        );
        assert_eq!(txns[0].postings.len(), 2);
        assert_eq!(txns[0].postings[1].account.full, "budget:food");
        assert_eq!(txns[0].postings[1].amount.get("$"), dec!(-7));
    }

    #[test]
    fn lenient_mode_keeps_unbalanced_transactions_with_a_warning() {
        let journal = parse(
            "2024-01-15 Bad\n    expenses:food  $50.00\n    assets:checking  $-40.00\n\n\
             2024-01-16 Good\n    expenses:food  $1\n    assets:checking\n",
        )
        .unwrap();
        // Strict (the default) still refuses, so edit validation keeps working.
        assert!(resolve_journal(&journal).is_err());

        let result = resolve_journal_lenient(&journal);
        assert_eq!(result.transactions.len(), 2);
        assert!(result.transactions[0].unbalanced);
        assert!(!result.transactions[1].unbalanced);
        assert_eq!(result.transactions[0].postings[1].amount.get("$"), dec!(-40));
        assert_eq!(result.warnings.len(), 1);
        assert_eq!(result.warnings[0].line, 1);
        assert!(result.warnings[0].message.contains("Unbalanced"), "{}", result.warnings[0].message);
    }

    #[test]
    fn overflow_warns_instead_of_panicking() {
        let text = "2024-01-01 a\n    x  79228162514264337593543950335 FOO\n    y\n\n\
                    2024-01-02 b\n    x  79228162514264337593543950335 FOO\n    y\n";
        let journal = parse(text).unwrap();
        let result = resolve_journal_lenient(&journal);
        assert_eq!(result.transactions.len(), 2);
        assert!(
            result.warnings.iter().any(|w| w.message.contains("too large")),
            "warnings: {:?}",
            result.warnings
        );
        // Strict resolution reports the same problem without panicking.
        let strict = resolve_journal(&journal).unwrap();
        assert!(!strict.warnings.is_empty());
        // And a Ledger can still be built over it.
        assert!(crate::ledger::Ledger::from_journal(&journal).is_ok());
    }
}
